server:
  #设置端口
  port: 8888
  max-http-header-size: 8192
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000

#spring配置
spring:
  #数据源配置
  datasource:
    name: springboot
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #地址
    url: jdbc:mysql://localhost:3306/cams?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 1009
#    password: Fan.1009
    type: com.alibaba.druid.pool.DruidDataSource
      #druid 设置
    druid:
      filter: stat
      #初始化大小
      initial-size: 1
      #最小等待连接数量
      min-idle: 1
      #最大连接数
      max-active: 20
      #超时设置
      max-wait: 86400
  #Aop
  aop:
    auto: true
    proxy-target-class: true
  #MVC
  mvc:
    view:
      prefix: /
      suffix: .html
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.demo.entity

#pagehelper配置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


